icons = "awesome5"

# Mouse
[[block]]
block = "bluetooth"
mac = "CF:1C:E8:D7:D7:31"

# Keyboard
[[block]]
block = "bluetooth"
mac = "C7:F1:C8:B9:CB:39"

# Phone
[[block]]
block = "bluetooth"
mac = "A4:50:46:77:72:9C"

[[block]]
block = "net"
device = "enp58s0f1"
ip = true
interval = 2

[[block]]
block = "net"
device = "wlp59s0"
bitrate = true
ssid = true
ip = true
interval = 2

[[block]]
block = "disk_space"

[[block]]
block = "memory"
format_mem = "{Mum}MB ({Mup}%)"

[[block]]
block = "cpu"
frequency = true

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C"
chip = "*-isa-*"
# inputs = ["Core 0"]

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "battery"
interval = 10
format = "{power} {percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%v %R"

