icons = "awesome5"

# Mouse
[[block]]
block = "bluetooth"
mac = "CF:1C:E8:D7:D7:31"

# Keyboard
[[block]]
block = "bluetooth"
mac = "C7:F1:C8:B9:CB:39"

# Phone
[[block]]
block = "bluetooth"
mac = "A4:50:46:77:72:9C"

[[block]]
block = "net"
device = "enp58s0f1"
format = "{ip} {speed_down} {speed_up}"
interval = 2

[[block]]
block = "net"
device = "wlp59s0"
format = "{ssid} {signal_strength} {ip} {speed_down} {speed_up}"
interval = 2

[[block]]
block = "disk_space"
format = "{icon} {path} {available}"

[[block]]
block = "memory"
format_mem = "{mem_used} ({mem_used_percents})"

[[block]]
block = "cpu"
interval = 3
format = "{utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}C"
chip = "*-isa-*"
# inputs = ["Core 0"]

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "battery"
interval = 10
format = "{power} {percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%F %R"

