#!/bin/sh

xrdb -merge ~/.config/x/Xresources &
xsetroot -cursor_name left_ptr &
xsetroot -solid black &
xset b off     # Disable beep sound
xset +fp /usr/share/fonts/local
xset fp rehash
setxkbmap fr
setxkbmap -option ctrl:nocaps
#xbindkeys

# For QGTKStyle to work
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

urxvtd -q -f -o
#bluetooth-applet &
#batterymon &
#xscreensaver -nosplash &
#volumeicon &
#xcompmgr -c -f -F -D 5 &
#xcompmgr &
#cairo-compmgr &
wmname LG3D &
#unclutter &
# gtk-redshift &
#wicd-gtk &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --transparent true --tint 0x0077 --height 20 --widthtype request &
ck-launch-session udiskie &
#anamnesis --start &
#xrandr --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal

exec xmonad
