# Prompt {{{
Black="$(tput setaf 0)"
BlackBG="$(tput setab 0)"
DarkGrey="$(tput bold ; tput setaf 0)"
LightGrey="$(tput setaf 7)"
LightGreyBG="$(tput setab 7)"
White="$(tput bold ; tput setaf 7)"
Red="$(tput setaf 1)"
RedBG="$(tput setab 1)"
LightRed="$(tput bold ; tput setaf 1)"
Green="$(tput setaf 2)"
GreenBG="$(tput setab 2)"
LightGreen="$(tput bold ; tput setaf 2)"
Brown="$(tput setaf 3)"
BrownBG="$(tput setab 3)"
Yellow="$(tput bold ; tput setaf 3)"
Blue="$(tput setaf 4)"
BlueBG="$(tput setab 4)"
LightBlue="$(tput bold ; tput setaf 4)"
Purple="$(tput setaf 5)"
PurpleBG="$(tput setab 5)"
Pink="$(tput bold ; tput setaf 5)"
Cyan="$(tput setaf 6)"
CyanBG="$(tput setab 6)"
LightCyan="$(tput bold ; tput setaf 6)"
NC="$(tput sgr0)" # No Color

case $(id -u) in
    0)
        STARTCOLOR=$LightRed;
        ;;
    *)
        STARTCOLOR=$LightGreen;
        ;;
esac

PS1="\[$STARTCOLOR\]\u@\[$LightBlue\]\h\[$NC\]:\[$Purple\]\w \[$NC\]\r\n\[$Cyan\]> \[$NC\]"
PS2="\[$Cyan\]> \[$NC\]"
# }}}

# Aliases {{{
alias chmod="chmod -c --preserve-root"
alias cp='cp -v --strip-trailing-slashes'
alias mk='mkdir -p -v'
alias mv='mv -v'
alias rename="rename -v"
alias rm='safe-rm -v'

alias l='ls -l'
alias la='ls -la'
alias lsa='ls -a'
alias l.='ls -d .*'
alias ls='ls --tabsize=0 --literal --color=auto --show-control-chars -p -h --group-directories-first -X'

alias df='df -hT'
#alias df="cdf -h"
#alias du='du -chs'
alias free='free -h'

alias diff="colordiff"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gcc="colorgcc"
#alias grep='grep --color=auto'
#alias make="colormake"

#alias emacs='emacsclient -c -n -a ""'
alias gdb="cgdb -q"
alias locate="locate -e"
alias mplayer="mplayer -msgcolor"
alias mutt='mutt -y'
alias octave="octave -q"
alias wget="wget -c"

#alias -p grep='ack'
#alias more='vimpager'
#alias less='vimpager'
alias pacman='pacman-color'
alias ping='mtr'
alias top="htop"
alias vim="emacs"
alias which='type -all'

alias my_indent='indent -bad -bap -bbo -bc -nbfda -br -brs -cbi0 -cdb -cdw -ce -ncs -di4 -fca -hnl -i4 -ip4 -l120 -lp -nlps -npcs -nprs -npsl -saf -sai -saw -sbi4 -sc -nsob -ss -ts4 -nut '

alias c='cp'
alias e='emacsclient -t -a ""'
alias E='SUDO_EDITOR="emacsclient -t" sudoedit' 
alias h='halt'
alias m='mutt'
alias o='xdg-open'
alias s='sudo'

#alias openports='sudo netstat --all --numeric --programs --inet'
alias listening-ports='sudo netstat -tlnp'
alias openports='sudo iptstate -o'
alias pg='mtr www.google.fr'
alias reco='sudo dhclient eth0'
alias volume='alsamixer -c 0'
alias dlpage='wget -nd -pHEKk'
alias wifiselect='sudo wifi-select wlan0'

alias http-on="sudo /etc/rc.d/lighttpd start"
alias http-off="sudo /etc/rc.d/lighttpd stop"
alias mysql-on="sudo /etc/rc.d/mysqld start"
alias mysql-off="sudo /etc/rc.d/mysqld stop"
alias bluetooth-on="sudo /etc/rc.d/bluetooth start"
alias bluetooth-off="sudo /etc/rc.d/bluetooth stop"
alias mpd-on="sudo /etc/rc.d/mpd start"
alias mpd-off="sudo /etc/rc.d/mpd stop"
alias wifi-on="sudo /etc/rc.d/net-auto-wireless start"
alias wifi-off="sudo /etc/rc.d/net-auto-wireless stop"
alias cups-on="sudo /etc/rc.d/cupsd start"
alias cups-off="sudo /etc/rc.d/cupsd stop"

alias wtf='dmesg'
alias rtfm='man'

if [ $UID -ne 0 ]; then
    alias reboot='sudo reboot'
    alias halt='sudo halt'
    alias up='sudo pacman-color -Syu && sudo diffpac'
    alias upgrade='sudo pacman-color -Syu && sudo diffpac'
    alias remove='sudo pacman-color -Rs'
    alias netcfg='sudo netcfg2'
fi
# }}}

# {{{ Auto-completion
complete -cf sudo
complete -cf man
# }}}

# {{{ Options
shopt -s cdspell
shopt -s cmdhist
shopt -s dirspell
shopt -s globstar
shopt -s histverify
shopt -s hostcomplete
shopt -s lastpipe
shopt -s no_empty_cmd_completion
# }}}

# Helpers {{{
lsmount()  { (echo "DEVICE PATH TYPE FLAGS" && mount | awk '$2=$4="";1') | column -t; }
sleep-on() { sudo rc.d stop fcron; }
ls-empty() { find . -type d -empty -print0 | xargs --null ls; }
rm-empty() { find . -type d -empty -print0 | xargs --null rmdir; }
u()        { wget -c $(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' `xclip -o`); }


proxy-on() {
    export http_proxy="http://localhost:8118/"
    export https_proxy="http://localhost:8118/"
    #export ftp_proxy="http://$username:$password@proxyserver:8080/"
    #export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
    echo -e "\nProxy environment variable set."
}
proxy-off() {
    unset HTTP_PROXY
    unset http_proxy
    unset HTTPS_PROXY
    unset https_proxy
    unset FTP_PROXY
    unset ftp_proxy
    echo -e "\nProxy environment variable removed."
} 
# }}}

stty -ixon
